---
# tasks file for zabbix-agent-install
  - name: Get zabbix-agent
    apt:
      deb: https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix-release/zabbix-release_6.0-5+debian12_all.deb
      
  - name: Update cash
    apt:
      update_cache: yes

  - name: install zabbix-agent
    apt:
      name: zabbix-agent
      state: present
  
  - name: Directory for logs
    command: mkdir -p /var/log/zabbix
    become_user: root
  
  - name: rights from Zabbix Agent
    command: chown zabbix /var/log/zabbix/
    become_user: root

  - name: Copy files from role's files directory 
    template: 
      src: "/etc/ansible/roles/zabbix-agent-install/templates/zabbix_agentd.conf.j2"
      dest: "/etc/zabbix/zabbix_agentd.conf"
    notify: restart zabbix-agent

  
