---
# vars file for install-zabbix
  packages:
    - apache2
    - postgresql
    - postgresql-contrib
    - python3-pexpect
    - python3-pip
    - python3-dev
    - python3-venv
    - python3-psycopg2
    - zabbix-server-pgsql
    - zabbix-frontend-php
    - php8.2-pgsql
    - zabbix-apache-conf
    - zabbix-sql-scripts
    - zabbix-agent
    
  pass_zabbixdb: zabbix
