---
# tasks file for install-zabbix
    - name: Add Zabbix repo
      shell: wget  https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix-release/zabbix-release_6.0-5+debian12_all.deb
      args:
        chdir: /tmp

    - name: install Zabbix repo
      shell: dpkg -i zabbix-release_6.0-5+debian12_all.deb
      args:
        chdir: /tmp

    - name: update cache
      apt:
        update_cache: yes

    - name: install dependency Zabbix
      apt:
        pkg: '{{ packages }}'
        state: present
      

    - name: Create new user PostgreSQL for Zabbix
      ansible.builtin.expect:
        command: sudo -u postgres createuser --pwprompt zabbix
        responses:
          (?i).*(Enter password for new role)(.*):
           - '{{ pass_zabbixdb }}'
          (?i).*(Enter it again)(.*):
           - '{{ pass_zabbixdb }}'

    - name: Create DB PostgreSQL for Zabbix
      shell: >
        sudo -u postgres createdb -O zabbix zabbix

    - name: Import scheme
      shell:
        zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | sudo -u zabbix psql zabbix

    - name: Install DBPassword in conf Zabbix
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: '^DBPassword='
        line: 'DBPassword=zabbix'
        
    - name: Restart Zabbix-agent
      service:
        name: zabbix-agent
        state: restarted
        enabled: yes

    - name: Restart Zabbix-server
      service:
        name: zabbix-server
        state: restarted
        enabled: yes
        
    - name: Restart Apache2
      service:
        name: apache2
        state: restarted
        enabled: yes
