[elk]
elastic.ru-central1.internal  

[kibana]
kibana.ru-central1.internal 

[webserv]
webserv-1.ru-central1.internal  
webserv-2.ru-central1.internal  

[zab]
zabbix.ru-central1.internal  

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p -q user@"'
ansible_ssh_private_key_file=/home/yastrebov/.ssh/id_ed25519